# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=210)),
                ('status', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], default='None', max_length=210)),
                ('price', models.IntegerField()),
                ('area', models.CharField(default='None', max_length=210)),
                ('rooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('MORE', 'More')], default='None', max_length=210)),
                ('bathroom', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='None', max_length=210)),
                ('address', models.CharField(default='None', max_length=210)),
                ('state', models.CharField(default='None', max_length=210)),
                ('code', models.CharField(default='None', max_length=210)),
                ('images', models.ImageField(upload_to='images')),
                ('info', models.TextField(default='None', max_length=1000)),
                ('parking', models.BooleanField(default=False)),
                ('air', models.BooleanField(default=False)),
                ('swimming', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('dealer_name', models.CharField(default='None', max_length=210)),
                ('dealer_email', models.EmailField(default='None', max_length=210)),
                ('dealer_number', phone_field.models.PhoneField(default='Not mentioned', max_length=210)),
                ('timpestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
