# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='dealer_number',
        ),
    ]
