# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 09:45
from __future__ import unicode_literals

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_dealer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dealer_number',
            field=phone_field.models.PhoneField(default=1, max_length=31),
            preserve_default=False,
        ),
    ]
