# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20190428_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='dealer_number',
            field=models.CharField(default='Not mentioned', max_length=210),
        ),
    ]
