# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20190428_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='dealer_email',
            field=models.EmailField(default='abc@gmail.com', max_length=210),
        ),
    ]
