# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20190428_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('S', 'Single Family '), ('A', 'Apartment'), ('C', 'Condo  '), ('M', 'Multi Family   '), ('V', 'Villa  '), ('O', 'Other  ')], default=1, max_length=240),
            preserve_default=False,
        ),
    ]
