# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20190428_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ManyToManyField(to='properties.Category'),
        ),
    ]
