# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20190428_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='properties.Category'),
        ),
    ]
