# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20190429_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='None', max_length=210),
        ),
    ]
