# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20190502_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('RENT', 'Rent'), ('SALE', 'Sale')], default='None', max_length=210),
        ),
    ]
