# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20190502_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
    ]
