# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20190502_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, help_text='Parking', verbose_name='Parking'),
        ),
    ]
