# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20190502_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=210),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('MORE', 'More')], default='1', max_length=210),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('RENT', 'Rent'), ('SALE', 'Sale')], default='Rent', max_length=210),
        ),
    ]
