# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20190506_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ImageField(default='images/20190327_154648_0001.png', upload_to='images'),
        ),
    ]
