# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_auto_20190506_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
    ]
