# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('CA', 'California'), ('NY', 'New york'), ('C', 'Chicago')], default='None', max_length=210),
        ),
    ]
